### ISSUE TITLE
Any body here?

### ISSUE THREAD

**Issue by AL-377** [MapRock/IntelligenceBusiness#1]

**Comment by MapRock** [comment]
Hi, 

This is Eugene. I'm here. 

What's your question? Just a caveat that I had some health issues the past few weeks and missed posting some code. Still in a bit of recovery mode.

But hopefully, I can answer your question.

Eugene

**Comment by AL-377** [comment]
Hello, I don't have any problems, just seeing that it's quiet here. 😁
Hope you'll get better soon!

**Comment by MapRock** [comment]
Hey Aiden,

Thank you. It looks like I'm out of commission for a few weeks - which is a like a few years in AI time ... hahaha.

From your icon, it looks like you play guitar? I've been practicing for almost four years now. It's only been within the last couple of months I feel like I've hit "intermediate".

Take care,

Eugene

**Comment by AL-377** [comment]
Hey Eugene,

What a coincidence, my friend! I play the guitar too. I started learning when I was 9, although it’s been on and off over the years. I first started with classical guitar, then moved on to electric guitar, and later to acoustic guitar. Nowadays, I don’t take lessons anymore; I just play for fun in my free time. Are you also practicing on your own? What style do you play?

AIdan

**Comment by MapRock** [comment]
Hey Aidan,

Same with me. I'm playing electric and acoustic, "old man" hard rock and
lighter rock, respectively. Yes, practicing on my own, all through Youtube
lessons. I decided to finally learn when Covid so nicely gave me two extra
hours of the day from not commuting ... haha. I'm also dabbling in Travis
picking and Hawaiian slack key on the acoustic (we're from Hawaii).

It's really great you started learning so early!!! My "boomer" hands took a
while to get it.

Let's continue conversation on regular email: ***@***.***

Take care,

Eugene

**Comment by AL-377** [comment]
Hey Eugene,
That's awesome! It seems like you're a really dedicated and passionate guitarist. I would love to continue chatting with you, but it looks like GitHub comments have hidden your email address. We can definitely keep in touch! My email is: aidan.lew.37@stu.pku.edu.cn.

Take care,
Aidan
